server:
  port: 8762
#  servlet:
#     context-path: /movies-registry

eureka:
   client:
      register-with-eureka: false
      fetch-registry: false

# server:
#   servlet:
#     context-path: /movies-registry

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
   application:
      name: eureka-movies-registry
      description: eureka-registry-for-movies-app
      clients:
         client1: movie-info
         client2: movie-rating
         client3: movie-catalog
