server:
  port: 8081
  servlet:
     context-path: /movie-info

spring:
  application:
    name: movie-info
    
management:
   endpoints:
      web:
         base-path: /actuator
         exposure:
            include: "*"
      health:
         show-details: always
         
info:
   application:
      name:   movie-info
      server:
         port: 8081
         servlet:
            context-path: /movie-info

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8762/eureka/
      enabled: true
